import { useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { AuthButton, AuthFeedback, AuthScreen, authStyles } from '@/features/auth/auth-ui';
import { useAuth } from '@/features/auth/session-provider';
import { completeOnboarding } from '@/features/onboarding/complete-onboarding';
import type { ExperienceLevel } from '@/types/user';

const EXPERIENCE_LEVELS: readonly {
  label: string;
  value: ExperienceLevel;
}[] = [
  { label: 'Newbie', value: 'newbie' },
  { label: 'Beginner', value: 'beginner' },
  { label: 'Intermediate', value: 'intermediate' },
  { label: 'Advanced', value: 'advanced' },
  { label: 'Pro', value: 'pro' },
];

export default function OnboardingScreen() {
  const { error: accountError, profile, refreshProfile, signOut } = useAuth();
  const [email, setEmail] = useState('');
  const [hasConfirmedAdult, setHasConfirmedAdult] = useState(false);
  const [experienceLevel, setExperienceLevel] = useState<ExperienceLevel | null>(null);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const submissionInFlight = useRef(false);

  const handleComplete = async () => {
    if (submissionInFlight.current) {
      return;
    }

    if (!hasConfirmedAdult) {
      setFeedback('You must confirm that you are 18 or older.');
      return;
    }

    if (!experienceLevel) {
      setFeedback('Choose your experience level.');
      return;
    }

    if (email.trim() && !isValidEmail(email)) {
      setFeedback('Enter a valid email address or leave it blank.');
      return;
    }

    submissionInFlight.current = true;
    setIsSubmitting(true);
    setFeedback(null);

    try {
      await completeOnboarding({
        email: email.trim() || null,
        experienceLevel,
      });
      refreshProfile();
    } catch (completionError) {
      setFeedback(getErrorMessage(completionError));
    } finally {
      submissionInFlight.current = false;
      setIsSubmitting(false);
    }
  };

  return (
    <AuthScreen
      description="A couple of details help other players know who’s on the court."
      eyebrow="Account setup"
      title="Complete your profile">
      <View style={styles.section}>
        <Text style={styles.label}>Your anonymous username</Text>
        <View style={styles.readOnlyField}>
          <Text style={styles.username}>{profile?.anonymous_username}</Text>
          <Text style={styles.readOnlyLabel}>Generated by CourtCheck</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>Email (optional)</Text>
        <TextInput
          accessibilityLabel="Optional email address"
          autoCapitalize="none"
          autoComplete="email"
          autoCorrect={false}
          editable={!isSubmitting}
          keyboardType="email-address"
          onChangeText={(value) => {
            setEmail(value);
            setFeedback(null);
          }}
          placeholder="you@example.com"
          style={authStyles.input}
          textContentType="emailAddress"
          value={email}
        />
        <Text style={authStyles.hint}>Used only as optional account contact information.</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>Experience level</Text>
        <View style={styles.options}>
          {EXPERIENCE_LEVELS.map((option) => {
            const isSelected = experienceLevel === option.value;

            return (
              <Pressable
                accessibilityRole="radio"
                accessibilityState={{ checked: isSelected }}
                disabled={isSubmitting}
                key={option.value}
                onPress={() => setExperienceLevel(option.value)}
                style={[styles.option, isSelected && styles.selectedOption]}>
                <Text style={[styles.optionText, isSelected && styles.selectedOptionText]}>
                  {option.label}
                </Text>
              </Pressable>
            );
          })}
        </View>
      </View>

      <Pressable
        accessibilityRole="checkbox"
        accessibilityState={{ checked: hasConfirmedAdult }}
        disabled={isSubmitting}
        onPress={() => setHasConfirmedAdult((isConfirmed) => !isConfirmed)}
        style={styles.checkboxRow}>
        <View style={[styles.checkbox, hasConfirmedAdult && styles.checkedCheckbox]}>
          <Text style={styles.checkmark}>{hasConfirmedAdult ? '✓' : ''}</Text>
        </View>
        <Text style={styles.checkboxLabel}>I confirm that I am 18 years of age or older.</Text>
      </Pressable>

      {feedback ? <AuthFeedback>{feedback}</AuthFeedback> : null}
      {!feedback && accountError ? <AuthFeedback>{accountError}</AuthFeedback> : null}
      <AuthButton
        disabled={!hasConfirmedAdult || !experienceLevel}
        isLoading={isSubmitting}
        onPress={() => void handleComplete()}
        title="Finish setup"
      />
      <AuthButton
        disabled={isSubmitting}
        onPress={() => void signOut()}
        title="Sign out"
        variant="secondary"
      />
    </AuthScreen>
  );
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : 'Something went wrong. Please try again.';
}

function isValidEmail(value: string) {
  const normalizedEmail = value.trim();
  return normalizedEmail.length <= 320 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail);
}

const styles = StyleSheet.create({
  section: {
    gap: 10,
  },
  label: {
    color: '#16263D',
    fontSize: 15,
    fontWeight: '800',
  },
  readOnlyField: {
    gap: 3,
    borderWidth: 1,
    borderColor: '#C8D5D3',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#F4F8F7',
  },
  username: {
    color: '#0E7C7C',
    fontSize: 18,
    fontWeight: '800',
  },
  readOnlyLabel: {
    color: '#6B7C87',
    fontSize: 12,
  },
  options: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  option: {
    borderWidth: 1,
    borderColor: '#C8D5D3',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
  },
  selectedOption: {
    borderColor: '#D76735',
    backgroundColor: '#FFF1EA',
  },
  optionText: {
    color: '#425466',
    fontSize: 14,
    fontWeight: '700',
  },
  selectedOptionText: {
    color: '#A9451C',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#7A8B92',
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
  },
  checkedCheckbox: {
    borderColor: '#0E7C7C',
    backgroundColor: '#0E7C7C',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  checkboxLabel: {
    flex: 1,
    color: '#354A5F',
    fontSize: 15,
    lineHeight: 22,
  },
});
